### ISSUE TITLE
Suggestion: Wiki or Debug feature to test results

### ISSUE THREAD

**Issue by Dajova** [Aireil/FlyTextFilter#3]
So i'm having a hard time figuring out which filter corresponds to which text. Could be nice to see a list or at least having a "debug" toggle on what filter does what and in what circumstances, if possible. Logging is not very handy, even if its "workable".

**Comment by Aireil** [comment]
Yes, ideally, there would be more information on every fly text types to be able to know which is which without logging them.
Although, once you've logged what you want to delete, it's pretty easy to filter the damage value or text in /xllog to find out the type.

**Comment by Aireil** [comment]
I've added a log tab and some information for the cryptic fly texts in 4.0.0.0.
It should now be quite easy to tell what is what, even if some fly texts change quite a lot depending on multiple criteria.

It will be in testing once this PR is merged: goatcorp/DalamudPlugins#2687
