### ISSUE TITLE
Force You as source for HoTs

### ISSUE THREAD

**Issue by ReidoK** [Aireil/FlyTextFilter#5]
First of all, thanks for the great plugin.

I was wondering if it would be possible to include a feature to set the source of heals over time as You, so that it would possible to filter the HoTs that Others apply, just like the one that exists for DoTs.

**Comment by Aireil** [comment]
HoTs are indeed similar to DoTs, however, the forcing on DoTs is to avoid filtering them when filtering auto attacks from Others. I'm not sure I understand the similar issue for HoTs, wouldn't you just want to remove Others for the HoTs type?

**Comment by ReidoK** [comment]
I'm trying to display flying text only for heals I cast and ticks from HoTs I applied (both on myself and on others), but I can't find a way to do the latter

**Comment by Aireil** [comment]
Hmmm, yes I see... Well the issue for HoTs is that they work as DoTs, meaning that if a HoT is on a player, the source and destination is that player. If it's on you, you're the source, although you may not have casted it. There's no way to see who's the real source for this tick, as it's the sum of all the HoTs. Unfortunately, I couldn't find a way to tell normal healing from healing ticks either.

**Comment by ReidoK** [comment]
Oh, I see D:
Thanks for your time and for the insight, though!
