### ISSUE TITLE
fly text to pop-up?

### ISSUE THREAD

**Issue by lunocjae** [Aireil/FlyTextFilter#6]
would an option to change the appearance/animation style of normal player-sourced fly texts into the more dynamic animation/placement style of popup texts be possible?

seeing as dot/chocobo/pet popups can be changed into normal fly texts, the reverse should be possible as well, if only for aesthetic purposes.

**Comment by Aireil** [comment]
I'm afraid you misunderstood what the setting is for. It's just for the filtering part of the plugin, it doesn't actually affect the fly text / pop-up text in any way.

I'll check, but I'm not sure that's something I would want to add. How do you imagine it working, just turning all fly texts in pop-up texts?

**Comment by lunocjae** [comment]
thanks for clearing up the misunderstanding. but essentially, yeah. I've always found the walls of scrolling text/numbers to be a bit distracting and cheap-looking, especially compared to other MMOs in XIV's metaphorical weight class.

**Comment by Aireil** [comment]
Closing as I wouldn't want to really go into modifications of the whole system itself and is thus out of scope for this plugin.
